spring:
  application:
    name: exam
  cloud:
    consul:
      host: localhost
      port: 8500
      config:
        enabled: false
  zipkin:
    base-url: http://localhost:9411/
server:
  port: 8200
