eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: course
  zipkin:
    base-url: http://localhost:9411/
  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        write:
          url: jdbc:mysql://127.0.0.1:6446/playground?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver
        read:
          url: jdbc:mysql://127.0.0.1:6447/playground?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8100
