eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    enabled: false
spring:
  application:
    name: course
  datasource:
    dynamic:
      hikari:
        connection-test-query: SELECT 1
        idle-timeout: 30000
        max-lifetime: 120000
        connection-timeout: 30000
      primary: write
      strict: false
      datasource:
        write:
          url: jdbc:mysql://127.0.0.1:6446/playground-course?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver
        read:
          url: jdbc:mysql://127.0.0.1:6447/playground-course?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/master.xml

server:
  port: 8100
logging:
  level:
    com.baomidou.dynamic: debug

playground:
  database:
    read-write-splitting:
      enabled: true
